### ISSUE TITLE
什么时候搞个1.5的安装

### ISSUE THREAD

**Issue by ghost** [liumiaocn/easypack#1]
什么时候搞个1.5的安装

**Comment by liumiaocn** [comment]
1.5的安装指的是kubernetes 1.5么。 这个已经有了：easypack_kubernetes_1.5.1_nowall.sh  而且在VPN内确认过了，不过使用的时候是用kubernetes的官方的baseurl，Easypack: 30分钟安装kubernetes1.5.1：http://blog.csdn.net/liumiaocn/article/details/54132880  找到稳定的国内的源替换一下就可以了

**Comment by ghost** [comment]
求一个yum源啊  只找到1.5.2的  现在脚本里边的是1.4.1的安装出来不对

**Comment by liumiaocn** [comment]
你好 cnicy
easypack_kubernetes_1.5.1_nowall.sh里面已经没有1.4相关的版本了
PROXY="kube-proxy-amd64:v1.5.1"
DISCOVERY="kube-discovery-amd64:1.0"
SCHEDULER="kube-scheduler-amd64:v1.5.1"
CONTROLLER="kube-controller-manager-amd64:v1.5.1"
APISERVER="kube-apiserver-amd64:v1.5.1"
PAUSE="pause-amd64:3.0"
ETCD="etcd-amd64:3.0.14-kubeadm"
DNS="kubedns-amd64:1.9 "
DNSMASQ="kube-dnsmasq-amd64:1.4"
HEALTHZ="exechealthz-amd64:1.2"
DASHBOARD="kubernetes-dashboard-amd64:v1.5.1"
METRICS="dnsmasq-metrics-amd64:1.0"

你把你找到的那个yum源，把脚本中的下面的换一下就可以了
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://files.rm-rf.ca/rpms/kubelet/
enabled=1
gpgcheck=0
EOF

剩下可能会出的问题应该在后面的kubeadm init下不去，下不去的时候检查一下/var/log/messages，里面会出kubernetes在拖哪个版本的image的信息
咱们在对应该一下翻过来的对应的版本号就可以了

不过好没有意义的事情，明明版本对的话分分钟就解决的问题，清华好像有几个学生在弄得一个源，下次看看能不能联系一下他们
帮助一下搜索不到版本有没有VPN的劳动人民

**Comment by ghost** [comment]
ok~感谢。
