### ISSUE TITLE
还是没安装成功。Created API client, waiting for the control plane to become ready

### ISSUE THREAD

**Issue by ghost** [liumiaocn/easypack#2]
安装程序卡在：
Created API client, waiting for the control plane to become ready
docker images

REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kube-controller-manager-amd64   v1.5.1              cd5684031720        8 weeks ago         102.4 MB
gcr.io/google_containers/kube-apiserver-amd64            v1.5.1              8c12509df629        8 weeks ago         124.1 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.5.1              6506e7b74dac        8 weeks ago         53.97 MB
gcr.io/google_containers/kube-proxy-amd64                v1.5.1              71d2b27b03f6        8 weeks ago         175.6 MB
gcr.io/google_containers/etcd-amd64                      3.0.14-kubeadm      856e39ac7be3        12 weeks ago        174.9 MB
gcr.io/google_containers/kubedns-amd64                   1.9                 26cf1ed9b144        12 weeks ago        47 MB
gcr.io/google_containers/dnsmasq-metrics-amd64           1.0                 5271aabced07        3 months ago        14 MB
gcr.io/google_containers/kube-dnsmasq-amd64              1.4                 3ec65756a89b        4 months ago        5.126 MB
gcr.io/google_containers/kube-discovery-amd64            1.0                 c5e0c9a457fc        4 months ago        134.2 MB
gcr.io/google_containers/exechealthz-amd64               1.2                 93a43bfb39bf        4 months ago        8.375 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        9 months ago        746.9 kB

镜像都下载成功了，是不是rpm的问题，我rpm是从谷歌直接下在rpm安装的
.sh脚本改动的地方
date |tee -a $INSTALL_LOG
echo "##Step 2: set install kubeadm etcd..." |tee -a $INSTALL_LOG
setenforce 0
yum install -y socat ebtables >> $INSTALL_LOG 2>&1
if [ _"$TYPE" = _"MASTER" ]; then
  echo "##Step 2: set repository and install kubeadm etc..." |tee -a $INSTALL_LOG
  rpm -ivh kubectl-1.5.1-0.x86_64.rpm >> $INSTALL_LOG 2>&1
  rpm -ivh kubernetes-cni-0.3.0.1.x86_64.rpm --nodeps --force >> $INSTALL_LOG 2>&1
fi
#yum install -y docker >> $INSTALL_LOG 2>&1
rpm -ivh kubelet-1.5.1-0.x86_64.rpm --nodeps --force >> $INSTALL_LOG 2>&1
rpm -ivh kubeadm-1.6.0-0.alpha.x86_64.rpm >> $INSTALL_LOG 2>&1
systemctl enable docker >> $INSTALL_LOG 2>&1
echo "#######Set docker proxy when needed. If ready, press any to continue..." |tee -a $INSTALL_LOG
read
systemctl restart docker >> $INSTALL_LOG 2>&1
systemctl enable kubelet & systemctl restart kubelet >> $INSTALL_LOG 2>&1

下面是/var/log/messages的日志，一直在循环报错

Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.491842   13597 feature_gate.go:181] feature gates: map[]
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.639852   13597 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.639888   13597 docker.go:376] Start docker client with request timeout=2m0s
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.666656   13597 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.675429   13597 manager.go:143] cAdvisor running in container: "/"
Feb 14 11:04:32 kube-master-2 kubelet: W0214 11:04:32.731776   13597 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: co
nnection refused
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.786243   13597 fs.go:117] Filesystem partitions: map[/dev/mapper/VolGroup-lv_root:{mountpoint:/ major:253 minor:0 fsType:ext4 blockSize:0} /dev
/sda1:{mountpoint:/boot major:8 minor:1 fsType:ext4 blockSize:0} /dev/mapper/VolGroup-lv_home:{mountpoint:/home major:253 minor:2 fsType:ext4 blockSize:0}]
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.788279   13597 manager.go:198] Machine: {NumCores:2 CpuFrequency:2194918 MemoryCapacity:1925455872 MachineID:35ee3a5bfcdd410284859ec6473a811d S
ystemUUID:35EE3A5B-FCDD-4102-8485-9EC6473A811D BootID:50c888ea-0035-4355-8ce0-bc2c5dd149e3 Filesystems:[{Device:/dev/mapper/VolGroup-lv_root Capacity:52710309888 Type:vfs Inodes:3276800 HasInodes:t
rue} {Device:/dev/sda1 Capacity:499337216 Type:vfs Inodes:128016 HasInodes:true} {Device:/dev/mapper/VolGroup-lv_home Capacity:11999027200 Type:vfs Inodes:753664 HasInodes:true}] DiskMap:map[253:0:
{Name:dm-0 Major:253 Minor:0 Size:53687091200 Scheduler:none} 253:1:{Name:dm-1 Major:253 Minor:1 Size:2113929216 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:12327059456 Scheduler:none} 
253:3:{Name:dm-3 Major:253 Minor:3 Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:68719476736 Scheduler:cfq}] NetworkDevices:[{Name:eth0 MacAddress:00:1c:42:4e:0c:60 Speed:0 M
tu:1500}] Topology:[{Id:0 Memory:2147000320 Cores:[{Id:0 Threads:[0] Caches:[]} {Id:1 Threads:[1] Caches:[]}] Caches:[{Size:6291456 Type:Unified Level:3} {Size:134217728 Type:Unified Level:4}]}] Cl
oudProvider:Unknown InstanceType:Unknown InstanceID:None}
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.812870   13597 manager.go:204] Version: {KernelVersion:3.10.0-327.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.12.5 Cadv
isorVersion: CadvisorRevision:}
Feb 14 11:04:32 kube-master-2 kubelet: W0214 11:04:32.814923   13597 container_manager_linux.go:205] Running with swap on is not supported, please disable swap! This will be a fatal error by defaul
t starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.815094   13597 kubelet.go:242] Adding manifest file: /etc/kubernetes/manifests
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.815111   13597 kubelet.go:252] Watching apiserver
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.817295   13597 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://10.211.55.80:6443/api/v1/services?resourc
eVersion=0: dial tcp 10.211.55.80:6443: getsockopt: connection refused
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.817321   13597 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://10.211.55.80:6443/api/v1/pods?fieldSe
lector=spec.nodeName%3Dkube-master-2.shared&resourceVersion=0: dial tcp 10.211.55.80:6443: getsockopt: connection refused
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.817352   13597 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://10.211.55.80:6443/api/v1/nodes?fieldSelector
=metadata.name%3Dkube-master-2.shared&resourceVersion=0: dial tcp 10.211.55.80:6443: getsockopt: connection refused
Feb 14 11:04:32 kube-master-2 kubelet: W0214 11:04:32.818118   13597 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.818140   13597 kubelet.go:477] Hairpin mode set to "hairpin-veth"
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.818267   13597 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.848207   13597 docker_manager.go:257] Setting dockerRoot to /var/lib/docker
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.848238   13597 docker_manager.go:260] Setting cgroupDriver to systemd
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.875245   13597 server.go:770] Started kubelet v1.5.1
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.875523   13597 event.go:208] Unable to write event: 'Post https://10.211.55.80:6443/api/v1/namespaces/default/events: dial tcp 10.211.55.80:644
3: getsockopt: connection refused' (may retry after sleeping)
Feb 14 11:04:32 kube-master-2 kubelet: E0214 11:04:32.875544   13597 kubelet.go:1145] Image garbage collection failed: unable to find data for container /
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.875554   13597 server.go:123] Starting to listen on 0.0.0.0:10250
Feb 14 11:04:32 kube-master-2 kubelet: I0214 11:04:32.876687   13597 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
Feb 14 11:04:33 kube-master-2 kubelet: E0214 11:04:33.134884   13597 kubelet.go:1634] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find
 data for container /

**Comment by liumiaocn** [comment]
好辛苦啊，你做的就是yum应该干的事情，给2点提示你在看看
1. 安装的时候不要使用 --nodeps --force ，这样依赖没有装完，所以可能不算完全正常安装完毕
2. 看看/var/log/messages, 看看有没有image的版本没有对上，如果有提示显示在pull其他版本的image的话，我们需要把镜像的版本也对应pull下来：在作1.4.1的时候碰到过类似的问题。但是当时忘记作memo了，关键词找不到了，可以使用grep -i pull /var/log/messages |grep -i image试试看看有没有

**Comment by ghost** [comment]
有联系方式活着讨论群没，加个好友吧～🤝🤝🤝🤝🤝

**Comment by liumiaocn** [comment]
1.6也快出来了，这样跟太辛苦了，本来很快就能解决的问题被绕来绕去，等我把DevOps的一个最佳实践的东西开个头之后，咱们看看从1.6开始看看能不能结束这种安装都很费劲的方式吧。抱着终将得到拯救的决心坚持下去吧，现在docker从1.13之后安装在centos上已经非常简单了，不必像1.12那样绕了，其实就是一个源的问题，大家可能都觉得不是问题，但是确实是卡住初学者的最大障碍。

**Comment by liumiaocn** [comment]
微信号：liumiaocn 请注明你是cnicy 不然不接

**Comment by ghost** [comment]
确实也是这样的，这个安装倒腾好久了，之前也是在虚拟机上装过，也是遇到各种问题啊。现在1.6还在aplha1找这个进度到release估计还要一个月左右。最近也在研究DevOps，见个群一起来完善和进步吧。
