### ISSUE TITLE
如果安装最新版本的k8s，step0-get-binaries.sh怎样修改？

### ISSUE THREAD

**Issue by mpv945** [liumiaocn/easypack#6]
可以直接修改step0-get-binaries.sh文件各组件的版本号进行最新版本的k8s安装嘛？还有每个版本的k8s怎样修改这些软件版本号？哪里可以有相关的文档说明？

**Comment by liumiaocn** [comment]
可以，k8s/ansible/download/vars/main.yml中有定义，可根据你的需要进行修改
var_ver_cfssl: R1.2
var_ver_k8s: v1.15.0
var_ver_etcd: v3.3.13
var_ver_docker: 18.09.7
var_ver_cni: v0.7.4
var_ver_flannel: v0.11.0
var_ver_pause: 3.1
var_ver_coredns: 1.2.6
var_ver_dashboard: v1.10.1
执行的日志被我顺手保留在CSDN上了，你可以参看一下，K8S新版出来一般我会试一下，目前都没有问题。
抱歉，回大家的issue太晚，完全没有注意到。文档多少可以看一下下面的内容
https://blog.csdn.net/liumiaocn/article/details/88413428
