### ISSUE TITLE
端口报错怎么回时

### ISSUE THREAD

**Issue by mpv945** [liumiaocn/easypack#7]
The connection to the server 192.168.0.3:6443 was refused - did you specify the right host or port?

**Comment by mpv945** [comment]
## create service
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by liumiaocn** [comment]
K8S 的Api Server没有正常设定，请先使用systemctl确认apiserver的状态。抱歉没有及时注意到，由于时间已经太久，请允许我直接关闭。有问题下次请尽可能提供更为详细一点的信息，因为这明显只是apiserver的服务没有正常启动的现象。
