### ISSUE TITLE
create output kubernetes binary dir failed for kubernetes v1.16.0

### ISSUE THREAD

**Issue by kylinai** [liumiaocn/easypack#8]
- name: create output kubernetes binary dir
  synchronize:
    src: "{{ var_download_tmp_dir_k8s }}/"
    dest: "{{ var_download_save_dir_k8s }}" 

binary files no long exist in server folder

**Comment by liumiaocn** [comment]
You can use download playbook to get all the binaries needed. You can find its usage in
https://liumiaocn.blog.csdn.net/article/details/96421940
In fact, just the following command executed, all the binaries will be downloaded and collected.
Command: ansible-playbook download/tests/test.yml
