### ISSUE TITLE
如何利用ansible部署多个节点？

### ISSUE THREAD

**Issue by sunhuaxu** [liumiaocn/easypack#9]
你好，我想用ansible部署1个master节点、2个node节点，如何修改common_vars.yml，或hosts。谢谢！

**Comment by liumiaocn** [comment]
你可以先参照k3s的方式部署的一主多从的方式，
* Ansible脚本方式：
https://github.com/liumiaocn/easypack/tree/master/containers/standard/rancher/k3s/ansible

* 使用说明
Ansible方式部署日志memo：https://liumiaocn.blog.csdn.net/article/details/103318341

* 脚本方式：
https://github.com/liumiaocn/easypack/tree/master/containers/standard/rancher/k3s/shell

* 使用说明
脚本方式的部署日志memo：https://liumiaocn.blog.csdn.net/article/details/103303659

**Comment by liumiaocn** [comment]
脚本方式的部署日志memo：https://liumiaocn.blog.csdn.net/article/details/103303659

**Comment by liumiaocn** [comment]
Ansible方式部署方式可参看如下说明：
https://editor.csdn.net/md?articleId=103725251

**Comment by liumiaocn** [comment]
已增加多节点部署方式，在1.15和1.17等版本已经验证
